services:
  - type: web
    name: sustainable-living-advisor
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PORT
        value: 10000
